project:
  type: website

website:
  title: "CloudForDMQ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - static_md/tutorials_links.md
      - about.qmd

left:
  - text: "Topics"
    menu: 
      - formats.qmd
      - DataManagement_MajorPlatforms.qmd
      - DataManagement_MediumPlatforms.qmd
      - DataManagement_UsefulToolsAndPlatforms.qmd
      - to_sort.qmd
      - to_investigate.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



