project:
  type: website

website:
  title: "CloudForDMQ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - static_md/tutorials_links.md
      - about.qmd

  sidebar:
    style : "docked"
    search: true
    contents:
        - formats.qmd
        - pages/DataManagement_MajorPlatforms.qmd
        - pages/DataManagement_MediumPlatforms.qmd
        - pages/DataManagement_UsefulToolsAndPlatforms.qmd
        - to_sort.qmd
        - to_investigate.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



